# Generated by Django 4.0 on 2022-01-04 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_author_book_tracker_tag_review_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tracker',
        ),
    ]
