# Generated by Django 4.0 on 2022-01-04 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_author_unique_author_book_unique_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='books',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='added_books', to='api.user'),
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='books', to='api.Genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='books', to='api.Tag'),
        ),
    ]
