# Generated by Django 4.0 on 2022-01-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_genre_books_remove_tag_books_book_added_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
