# Generated by Django 4.0 on 2022-01-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_author_author_unique_author_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pub_year',
            field=models.IntegerField(null=True),
        ),
    ]
